// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtgqxqcskbylodxihfkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10Z3F4cWNza2J5bG9keGloZmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODM5MjAsImV4cCI6MjA3MzM1OTkyMH0.LLZ7yP7Hbem6FSke28Y1ZLDmc-tuFW4dRHGC61dTV68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});